### PR TITLE
guild member remove logging

### PR DESCRIPTION
**Pull request by Sniped**
whenever mrscopes leaves, we celebrate, but whenever anyone else leaves, we don't celebrate!

### CODE REVIEW

**Comment by MrScopes** [comment]
Doesn't use emojis, booooo!

**Comment by Sniped** [comment]
i fix

**Comment by MrScopes** [comment]
bad style
```js
module.exports = (client, member) => {
  if (member.user.id === '496477678103298052') {
    client.channels.get('546937756945743893').send('fuck yeah he's gone now');
  } else return client.channels.get('546937756945743893').send('not today, he'll be gone another day');
}
```
would be better if
```js
module.exports = (client, member) => {
  if (member.user.id === '496477678103298052') return client.channels.get('546937756945743893').send('fuck yeah he's gone now');
 client.channels.get('546937756945743893').send('not today, he'll be gone another day');
}
```

**Comment by Sniped** [comment]
but they function the same 🤔

**Pull request closed without merging**
